project:
  type: website
  output-dir: docs
website:
  title: "Endless"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Economics-Lab"
        menu: 
          - about.qmd
          - project.qmd
          - program.qmd
      - text: "Network science"
        menu:
          - lecture.qmd
          - lecture_note.qmd
      - text: "Vision and action plan"
        menu: 
          - People.qmd
          - Member_Portal.qmd
      - text: "clinical psychology"
        menu:
          - nero.qmd

      - text: "industrial organization theory"
        menu:
          - 산업 무역 보세 

      - text: "Jurispredence"
        menu:
          - constitution_ROK.qmd
          - civil_ROK.qmd
      - text: "Art-Dance"
        menu:
          -한국무용의_실제.qmd
      - text: "Linguistics and NLP"
        menu:
          - Linguistics_and_NLP.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true